#!/bin/sh

function install () {
  echo 'No install has been added yet, feel free to open a pull request'
}

function build () {
  echo 'No build has been added yet, feel free to open a pull request'
}
