# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "file", source: "scripts", destination: "scripts"
  config.vm.provision "file", source: "hello.swift", destination: "hello.swift"

  config.vm.provision "shell", inline: <<-SHELL
    echo 'source ~/scripts' >> .bashrc
  SHELL

  # OPTIONAL: increase ram and cpus to speed up builds
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end
