#!/bin/sh

function install () {
  apt-get update
  # install emscripten prerequisits
  sudo apt-get install -y build-essential cmake python nodejs git-core

  # install emscripten sdk manager
  wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  tar -zxvf emsdk-portable.tar.gz
  echo 'export PATH="$PATH:/home/ubuntu/emsdk-portable"' >> /home/ubuntu/.bashrc

  # install rustup, rust version manager
  curl https://sh.rustup.rs -sSf | sh -s -- -y

  # ensure emscripten and rustup are in environment
  source .bashrc

  # install emscripten
  emsdk update
  emsdk install sdk-incoming-64bit
  emsdk activate sdk-incoming-64bit

  # install rust wasm target
  rustup target add wasm32-unknown-emscripten
}

function build () {
  rustc --target=wasm32-unknown-emscripten hello.rs -o hello.html
}
