#!/bin/sh

function install () {
  wget https://github.com/JetBrains/kotlin-native/releases/download/v0.5/kotlin-native-linux-0.5.tar.gz
  tar -zxvf kotlin-native-linux-0.5.tar.gz
}

function build () {
  ./kotlin-native-linux-0.5/bin/konanc hello.kt -target wasm32
}
